### ISSUE TITLE
The /banks page includes "Mock bank"

### ISSUE THREAD

**Issue by AranScope** [arussellsaw/budgie#2]
I believe due to using the TrueLayer trial account, [the /banks page](https://youneedaspreadsheet.com/banks) includes "Mock Bank" as the top entry. The list is also not alphabetically ordered, which I guess is why this appears at the top.

**Comment by skos-ninja** [comment]
This is fixed as of #3 🎉  
The providers endpoint with TrueLayer will always return mock bank so you just have to manually filter it out.

**Comment by Sherlouk** [comment]
Good spot Jake! 😂

**Comment by arussellsaw** [comment]
thanks all! 🙏
